# ==========================================================
# gRPC
# HAProxy :8084 -> OpenResty :8085 -> Apache :8083 -> Xray
# ==========================================================

server {

    listen 8085 http2;
    server_name _;

    limit_conn conn_limit 512;

    location = /openresty/trojan-grpc {

        limit_req
            zone=grpc_limit
            burst=60
            nodelay;

        grpc_pass grpc://apache_grpc;

        grpc_set_header Host $host;

        grpc_read_timeout 3600s;
        grpc_send_timeout 3600s;
    }

    location = /openresty/vmess-grpc {

        limit_req
            zone=grpc_limit
            burst=60
            nodelay;

        grpc_pass grpc://apache_grpc;

        grpc_set_header Host $host;

        grpc_read_timeout 3600s;
        grpc_send_timeout 3600s;
    }

    location = /openresty/vless-grpc {

        limit_req
            zone=grpc_limit
            burst=60
            nodelay;

        grpc_pass grpc://apache_grpc;

        grpc_set_header Host $host;

        grpc_read_timeout 3600s;
        grpc_send_timeout 3600s;
    }

    location = /openresty/ss-grpc {

        limit_req
            zone=grpc_limit
            burst=60
            nodelay;

        grpc_pass grpc://apache_grpc;

        grpc_set_header Host $host;

        grpc_read_timeout 3600s;
        grpc_send_timeout 3600s;
    }
}

upstream apache_grpc {

    server 127.0.0.1:8083;

    keepalive 64;
}
